In [2]:
import numpy as np

#NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[9]

np.int64(20)

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [9]:
arr_slice = arr[1:9:2]
arr_slice

array([12, 14, 16, 18])

#NUMPY INDEXING AND SLICING OF MATRIX

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[5]

array([26, 27, 28, 29, 30])

In [13]:
arr[3]

array([16, 17, 18, 19, 20])

In [14]:
arr[0,0]

np.int64(1)

In [15]:
arr[0,4]

np.int64(5)

In [16]:
arr[5,4]

np.int64(30)

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [20]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [22]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

#BOOLEAN INDEXING

In [28]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [30]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])