#Array Operations

In [2]:
import numpy as np

**Arithmetic operations**

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [4]:
arr2 = a1 ** a2
arr2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [5]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [6]:
arr+10

array([20, 30, 40, 50])

In [7]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

**Deep and shallow copy**

In [9]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
a[4:6] * 10

array([50, 60])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a
b = a #deep copy

In [17]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a #changes made i copy were also reflected in the main array

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
b = a.copy() #shallow copy
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
b[6] = 55
b

array([99,  2,  3,  4,  5,  6, 55,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a #clearly we can see the difference

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operations**

In [28]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.arange(5,9).reshape(2,2)
mat1

array([[1, 2],
       [3, 4]])

In [29]:
mat2

array([[5, 6],
       [7, 8]])

In [30]:
#matrix multiplication
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [31]:
#Transpose
mat1.T

array([[1, 3],
       [2, 4]])

#Advance Array Manipulations

**Stacking Array**

In [32]:
#we only have to use vectors not matrix in stacking
mat1

array([[1, 2],
       [3, 4]])

In [33]:
mat2

array([[5, 6],
       [7, 8]])

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

**Spliting Array**

In [37]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [40]:
a = np.vsplit(c,2)

In [41]:
for i in a:
  print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
