#Importing the numpy package

In [1]:
import numpy as np

#Basic Array Operations

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3.4,"hello"]
a

[1, 2, 3.4, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3.4', 'hello'], dtype='<U32')

In [12]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

1-D are Vectors |
2-D are Matrices |
more than 2 are called as Tensors

In [13]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Array generation functions


In [14]:
#arange function
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr2 = np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [16]:
#generate zeros
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [17]:
arr4 = np.zeros((4,8))
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
#generate ones
arr5 = np.ones(6)
arr5

array([1., 1., 1., 1., 1., 1.])

In [21]:
arr6 = np.ones((8,4))
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
#linspace - Linear Spacing
#this is used to generate the elements in an array such that they have linear spaces between them.
arr7 = np.linspace(1,6,2)
arr7

array([1., 6.])

In [23]:
arr8 = np.linspace(1,5,10)
arr8

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
arr9 = np.linspace(0,1,100)
arr9

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

#Random Generation function


In [ ]:
#numpy with random library
arr10 = np.random.rand(5)
arr10

In [30]:
np.random.randn(10)

array([-1.09123511, -0.49377659, -1.10217925, -1.37740052,  1.42816822,
       -0.99070189,  0.42775623,  0.38934046, -1.01788275,  1.38689638])

In [31]:
np.random.randint(10,20,10)

array([13, 18, 18, 19, 17, 16, 14, 13, 15, 16])

#Array Attributes


In [33]:
#shape of the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int64')

#Array Methods


In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [45]:
np.sum(arr,axis=0) #sum of all the elements in each column

array([12, 15, 18])

In [46]:
np.sum(arr,axis=1) #sum of all the elements in each row

array([ 6, 15, 24])

In [47]:
arr.mean() #gives the mean

np.float64(5.0)

In [48]:
arr.std() #gives the std deviation

np.float64(2.581988897471611)

In [49]:
arr.argmax() #index of max element

np.int64(8)

In [50]:
arr.argmin() #index of min element

np.int64(0)

#Reshaping and resizing

In [54]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])