In [1]:
import numpy as np

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Questions**

In [2]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [4]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [7]:
#Find the average age of students.
avg_age = np.mean(data[:,0])
avg_age

np.float64(18.4)

In [8]:
#Extract Math marks of all students.
math_marks = data[:,1]
math_marks

array([85, 92, 76, 65, 90])

In [11]:
#Find the highest Science mark.
science_marks = data[:,2]
highest_science_marks = np.max(science_marks)
highest_science_marks

np.int64(95)

In [14]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [15]:
#Increase Math marks of all students by 5.
data[:,1] = data[:,1] + 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [18]:
#Find how many students are younger than 19.
num = data[data[:,0] < 19]
num.shape[0]

3

In [21]:
#Calculate the average marks in each subject (column-wise mean).
mean2 = np.mean(data[:,1])
mean3 = np.mean(data[:,2])
print(mean2,mean3)

86.6 83.2


In [23]:
#Get data of students who scored at least 80 in both subjects.
result = data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]
result

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [24]:
#Replace all Science marks < 75 with 0.
data[data[:, 2] < 75, 2] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])